image: Visual Studio 2019

install:
- cmd: choco install gitversion.portable --version 5.1.3 -y
- cmd: choco install dotnetcore-sdk --version 3.1.201 -y

before_build:
- cmd: gitversion /l console /output buildserver /updateassemblyinfo

build_script:
- cmd: dotnet restore src/Moq.Contrib.ArgumentCaptor.csproj
- cmd: dotnet build src/Moq.Contrib.ArgumentCaptor.csproj /p:Deterministic=true /p:ContinuousIntegrationBuild=true -c Release --no-restore
- cmd: dotnet pack src/Moq.Contrib.ArgumentCaptor.csproj -p:PackageVersion=%GitVersion_NuGetVersion% -c Release --no-build --output %APPVEYOR_BUILD_FOLDER%/artifacts/

test_script:
- cmd: dotnet test

artifacts:
- path: artifacts/*