image: Visual Studio 2019

install:
- cmd: choco install gitversion.portable --version 5.1.3 -y
- cmd: choco install dotnetcore-sdk --version 3.1.201 -y

before_build:
- cmd: gitversion /l console /output buildserver

build_script:
- cmd: dotnet restore
- cmd: dotnet build -p:AssemblyVersion=%AssemblySemVer% -p:AssemblyFileVersion=%AssemblyFileVersion% -p:AssemblyInformationalVersion=%AssemblyInformationalVersion% -p:ContinuousIntegrationBuild=true -c Release --no-restore
- cmd: dotnet pack -p:ContinuousIntegrationBuild=true -p:PackageVersion=%GitVersion_NuGetVersion% -c Release --no-build --output %APPVEYOR_BUILD_FOLDER%/artifacts/

test_script:
- cmd: dotnet test

artifacts:
- path: artifacts/*

deploy:
  provider: NuGet
  api_key:
    secure: 1XK6ZaBwc744xb1siMJBzqQN08IpfOUftIVtkThmkMugTJGZK5rrnnSua85hS/PR
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true